import XCTest
@testable import YameteCore
@testable import SensorKit

/// Ring 2 onion-skin for `USBSource` — DOCUMENTED RING 3 GAP.
///
/// `USBSource` subscribes to USB device arrival/termination via
/// `IOServiceAddMatchingNotification(port, kIOFirstMatchNotification, ...)`
/// and `kIOTerminatedNotification` against `IOServiceMatching(kIOUSBDeviceClassName)`.
/// The transport layer is a kernel-mode mach port (`IONotificationPortRef`)
/// posted by the IOKit family driver when a USB device's `IOService` lifecycle
/// changes. Userspace cannot synthesize these notifications — they are
/// generated by `kIOUSBDeviceClassName` in the kernel and delivered to the
/// matching ports of every registered process. There is no
/// `NSNotificationCenter` / `NSWorkspace` surface that mirrors them.
///
/// Why this is a TRANSPORT-LAYER gap, not a logic-layer gap:
///   Ring 1 (`Tests/MatrixUSBSource_Tests.swift`) drives `_injectAttach` /
///   `_injectDetach`, which yield through the SAME `AsyncStream` continuation
///   the IOKit callback yields into and run through the SAME `shouldPublish`
///   debounce + `bus.publish` fan-out. The only path NOT covered by Ring 1
///   is the kernel→userspace mach-port hop and the `IOIteratorNext` /
///   `IORegistryEntryCreateCFProperty` lookup the production callback runs
///   to resolve `vendorID` / `productID` from the `io_object_t`. Both are
///   kernel-mediated and cannot be exercised from userspace.
///
/// Manual validation procedure for the transport layer:
///   1. Build & run the app (`make install`).
///   2. Plug a USB device (e.g. flash drive) into a host port.
///   3. Observe the bus publishes exactly one `.usbAttached` reaction with
///      vendor/product IDs that match `system_profiler SPUSBDataType` for
///      the device.
///   4. Unplug. Observe one `.usbDetached`.
///   5. Plug + unplug 5x rapidly within the 50 ms debounce window
///      (`ReactionsConfig.usbDebounce`). Observe debounce collapses
///      duplicates per (vendorID, productID) key.
@MainActor
final class MatrixL2_System_USB_Tests: XCTestCase {

    func test_l3_gap_iokit_matching_notification_unpostable() throws {
        throw XCTSkip("""
            USBSource subscribes to IOServiceAddMatchingNotification on \
            kIOUSBDeviceClassName. Mach-port notifications from the IOKit \
            kernel family cannot be synthesized from userspace — there is \
            no NotificationCenter/NSWorkspace surface mirroring them. \
            Ring 1 _injectAttach/_injectDetach covers the production handler \
            logic (AsyncStream drainer + shouldPublish debounce + bus.publish). \
            This is a transport-layer-only gap. See file header for manual \
            validation procedure.
            """)
    }

    func test_l3_gap_kIOFirstMatchNotification_replay_burst_unpostable() throws {
        throw XCTSkip("""
            The boot-time replay burst (one kIOFirstMatchNotification per \
            currently-attached USB device) is also kernel-emitted and \
            unpostable from userspace. Ring 1 covers the `isInitialReplay` \
            suppression flag via _testEmit pattern. Manual validation: \
            launch the app with a USB device already attached and verify \
            no .usbAttached fires at startup.
            """)
    }

    func test_l3_gap_kIOTerminatedNotification_unpostable() throws {
        throw XCTSkip("""
            The detach side (kIOTerminatedNotification) is the same kernel \
            transport as attach. Userspace cannot post it. Ring 1 \
            _injectDetach drives the same callback signature the kernel \
            would. Manual validation: unplug a USB device while the app is \
            running and verify a .usbDetached publishes within ~10 ms.
            """)
    }

    func test_l3_gap_io_iterator_next_unpostable() throws {
        throw XCTSkip("""
            The production callback runs IOIteratorNext + \
            IORegistryEntryCreateCFProperty to resolve vendor/product IDs \
            from the io_object_t the kernel hands it. The io_iterator_t \
            cannot be synthesized from userspace. Ring 1 _injectAttach \
            takes vendor/product strings directly, exercising the same \
            yield path the post-resolution callback drives. Manual \
            validation: confirm published USBDeviceInfo.vendorID/productID \
            match the actual device's USB descriptor.
            """)
    }
}
